version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ml_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3306:3306'

    volumes:
        - ./init:/docker-entrypoint-initdb.d

  nexclipper-alerthub:
    build: .
    restart: always
    container_name: nexclipper-alerthub
    env_file:
      - .env.sample.local
    ports:
      - 5055:5055
