apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_IMAGE_NAME}-configmap
  labels:
    app: ${APP_IMAGE_NAME}
data:
  ID_PORT: "5055"
  ID_ENV: development
  ID_DB_CONFIG_HOST: "mariadb-primary.mariadb.svc.cluster.local"
  ID_DB_CONFIG_USER: root
  ID_DB_CONFIG_PORT: "3306"
  ID_DB_CONFIG_DB_NAME: ml_db
  ID_DB_CONFIG_POOL_MIN: "2"
  ID_DB_CONFIG_POOL_MAX: "7"
  ID_JWT_SECRET_KEY: test123!
  ID_LOG_FORMAT: combined
  ID_CORS_ORIGIN: "true"
  ID_CORS_CREDENTIALS: "true"
  ID_SUDORY_X_AUTH_TOKEN: "SUDORY"
  ID_X_AUTH_TOKEN: "Bearer ALERTHUB"
  ID_WAIT_MS_SEC: "1"
  ID_LOG_SILENCE_RESPONSE: "true"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_IMAGE_NAME}
spec:
  selector:
    matchLabels:
      app: ${APP_IMAGE_NAME}
  template:
    metadata:
      labels:
        app: ${APP_IMAGE_NAME}
    spec:
      containers:
      - name: ${APP_IMAGE_NAME}
        image: ${IMG_TAG_TO_DEPLOY}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 600m
            memory: 512Mi
          requests:
            cpu: 400m
            memory: 256Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 1002
          capabilities:
            drop:
              - SETUID
              - SETGID
        livenessProbe:
          tcpSocket:
            port: 5055
          initialDelaySeconds: 15
          timeoutSeconds: 15
        envFrom:
          - configMapRef:
              name: ${APP_IMAGE_NAME}-configmap
        volumeMounts:
          - name:  log
            mountPath:  /var/log
        env:
          - name: ID_DB_CONFIG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: mariadb-root-password
        ports:
        - containerPort: 5055
      volumes:
        - name:  log
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_IMAGE_NAME}
spec:
  selector:
    app: ${APP_IMAGE_NAME}
  type: LoadBalancer
  ports:
  - port: 5055
    targetPort: 5055
