apiVersion: v1
kind: Namespace
metadata:
  name:  nc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  ${APP_IMAGE_NAME}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_IMAGE_NAME}-configmap
  labels:
    app: ${APP_IMAGE_NAME}
data:
  NC_AH_PORT: "5055"
  NC_AH_ENV: production
  NC_AH_DB_CONFIG_HOST: "mariadb-primary.mariadb.svc.cluster.local"
  NC_AH_DB_CONFIG_DB_NAME: ml_db
  NC_AH_DB_CONFIG_POOL_MIN: "1"
  NC_AH_DB_CONFIG_POOL_MAX: "5"
  NC_AH_JWT_SECRET_KEY: test123!
  NC_AH_LOG_FORMAT: debug
  NC_AH_CORS_ORIGIN: "true"
  NC_AH_CORS_CREDENTIALS: "true"
  NC_AH_SUDORY_X_AUTH_TOKEN: "SUDORY"
  NC_AH_X_AUTH_TOKEN: "'Bearer ALERTHUB'"
  NC_AH_WAIT_MS_SEC: "1"
  NC_AH_LOG_SILENCE_RESPONSE: "true"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_IMAGE_NAME}
spec:
  selector:
    matchLabels:
      app: ${APP_IMAGE_NAME}
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: 'nexclipper-app'
        vault.hashicorp.com/agent-inject-secret-ncdb-admin-login: 'kv/database/ncdb'
        vault.hashicorp.com/agent-inject-template-ncdb-admin-login: |
          {{- with secret "kv/database/ncdb" -}}
          NC_AH_DB_CONFIG_USER={{ .Data.data.username }}
          NC_AH_DB_CONFIG_PASSWORD={{ .Data.data.password }}
          {{- end -}}
      labels:
        app: ${APP_IMAGE_NAME}
    spec:
      serviceAccountName: ${APP_IMAGE_NAME}
      containers:
      - name: ${APP_IMAGE_NAME}
        image: ${IMG_TAG_TO_DEPLOY}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 600m
            memory: 512Mi
          requests:
            cpu: 400m
            memory: 256Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 1002
          capabilities:
            drop:
              - SETUID
              - SETGID
        livenessProbe:
          tcpSocket:
            port: 5001
          initialDelaySeconds: 15
          timeoutSeconds: 15
        volumeMounts:
          - name:  log
            mountPath:  /var/log
        envFrom:
          - configMapRef:
              name: ${APP_IMAGE_NAME}-configmap
        ports:
        - containerPort: 5001
      volumes:
        - name:  log
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_IMAGE_NAME}
spec:
  selector:
    app: ${APP_IMAGE_NAME}
  ports:
  - port: 5001
    targetPort: 5001
